version: '3.9'

services:
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:${CLICKHOUSE_TAG}
    restart: always
    volumes:
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
    networks:
      - emqx_bridge
