version: '3.9'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: always
    volumes:
      - ./clickhouse/users.xml:/etc/clickhouse-server/usert.d/users.xml
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    expose:
      - "8123"
    ports:
      - "8123:2181"
    networks:
      - emqx_bridge
