version: '3'

services:
  mysql_server:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: public
      MYSQL_DATABASE: mqtt
    volumes:
      - ../../_build/emqx/lib/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/ca.pem:/etc/certs/ca-cert.pem
      - ../../_build/emqx/lib/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/server-cert.pem:/etc/certs/server-cert.pem
      - ../../_build/emqx/lib/emqx_auth_mysql/test/emqx_auth_mysql_SUITE_data/server-key.pem:/etc/certs/server-key.pem
    command:
      --bind-address 0.0.0.0
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --skip-symbolic-links
      --ssl-ca=/etc/certs/ca.pem
      --ssl-cert=/etc/certs/server-cert.pem
      --ssl-key=/etc/certs/server-key.pem
    networks:
      - emqx_bridge

  redis_server:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    command:
      - redis-server
      - "--bind 0.0.0.0 ::"
    restart: always
    networks:
      - emqx_bridge

  mongo_server:
    container_name: mongo
    image: mongo:4.1
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt
    command: --bind_ip_all
    networks:
      - emqx_bridge

  pgsql_server:
    container_name: pgsql
    image: postgres:11
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: public
      POSTGRES_USER: root
      POSTGRES_DB: mqtt
    networks:
      - emqx_bridge

  ldap_server:
    container_name: openldap
    build: ./emqx-ldap
    image: emqx-ldap:1.0
    ports:
      - 389:389
    restart: always
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
